<?php

define('BASE_PATH', dirname(__DIR__, 2) . DIRECTORY_SEPARATOR);
define('CONTROLLER_PATH', BASE_PATH . 'App' . DIRECTORY_SEPARATOR . 'Controllers' . DIRECTORY_SEPARATOR);
define('MODEL_PATH', BASE_PATH . 'App' . DIRECTORY_SEPARATOR . 'Models' . DIRECTORY_SEPARATOR);
define('VIEW_PATH', BASE_PATH . 'Views' . DIRECTORY_SEPARATOR);



